### ISSUE TITLE
Bring Repository up to standards

### ISSUE THREAD

**Issue by ZainlessBrombie** [ZainlessBrombie/NMS-Unlocked#1]
- add readme explaining the plugin
- add license file (private use / no liability)

**Comment by RedSpeeds** [comment]
Question would it be allowed for us the shade in NMC unlocked into our plugin jars to avoid having to give the user another dependency?

**Comment by ZainlessBrombie** [comment]
Hi :)
The plugin is not safe to shadow in it's current state. It also needs to load before all other plugins, including the one that is using it, though that would only apply if the Main class is causing version dependent classes to load.

Instead, you can include the jar whole and then save it to the plugins folder manually *if not already present, in this version or another* and load it using bukkits mechanism for loading plugins. Though my license currently does not reflect that usage, you are allowed to use it that way if you need it right now (and give credit accordingly ofc, I'd love for the tool to gain popularity ^_^), I'll see that I update the plugin to be shadeable or similiar (including the license upgrade) as soon as I can :)

Cheers <3

**Comment by RedSpeeds** [comment]
Thanks a lot
