### ISSUE TITLE
Make plugin shadeable or provide includeable code

### ISSUE THREAD

**Issue by ZainlessBrombie** [ZainlessBrombie/NMS-Unlocked#3]
-> A part of the plugin can be included in other plugins
-> Does not conflict with other plugins also using the lib
-> Does not conflict with the main plugin
-> attaches to the main plugin (if present) to transmit statistics
-> What to do if attach not supported? Download actual plugin?

**Comment by RedSpeeds** [comment]
When will this be done?

**Comment by ZainlessBrombie** [comment]
Hey there! :)
I currently have a lot of real life circumstances, but I'll see if I can get to it within the next few weeks. Sorry that this is taking so long and thanks for your patience!
Cheers

**Comment by ZainlessBrombie** [comment]
Since this would only work on jdk installations (not the norm) and thus be more limiting than running as a java agent, I am closing this in favor of a new project that when done instead takes a compiled jar and rewrites the bytecode to use cached reflection, enabling it to operate independently, if at ever so slighly reduced performance. This plugin will continue to exist for serverowners.
