### ISSUE TITLE
Config prefixdeny

### ISSUE THREAD

**Issue by SHADOWDANCH** [ZainlessBrombie/NMS-Unlocked#4]
To get prefixdeny work you need write 'prefixdeny :com.pkg' not 'prefixdeny: com.pkg'.
`.filter(line -> line.startsWith("prefixdeny :"))`

 _Sry for my english._

**Comment by ZainlessBrombie** [comment]
Ooops mistyped
Fixed you now need to type "prefixdeny: com.pkg", thanks a lot :)
