### ISSUE TITLE
Elapsed Spigot and NMS Unlocked

### ISSUE THREAD

**Issue by ZeeNatDev** [ZainlessBrombie/NMS-Unlocked#6]
Currently I am trying to using a custom spigot and NMS. But this custom spigot uses a license key, NMS does not have an option to input a key to use to connect to the spigot. When ever I load it using the same method but using a default spigot version it works. Was wondering if there was a feature for that?

**Comment by ZainlessBrombie** [comment]
Heyho!  
So if I understand you correctly you can't start the custom spigot with NMS because it does not recognize your license key, correct?

How are you starting your server and how are you inputting your license key?

**Comment by RedSpeeds** [comment]
Hey spigot developer here. According to our license it is illegal for them to sell software based of spigot so if you would be so kind to forward us the name and possibly the site we could forward this to the administrator.

**Comment by ZeeNatDev** [comment]
> Heyho!
> So if I understand you correctly you can't start the custom spigot with NMS because it does not recognize your license key, correct?
> 
> How are you starting your server and how are you inputting your license key?

Hello ZainlessBrobie,
Sorry for the late reply, From here on out I'll be faster to reply. But currently I have the license key in a license.txt file and the spigot recognizes that, then uses that to enable the spigot to work and to successfully boot. I am starting my server using this argument to recognize the NMS attachment.
`java -javaagent:<NMS Unlocked jar>.jar`
Thanks, PrePay.



> Hey spigot developer here. According to our license it is illegal for them to sell software based of spigot so if you would be so kind to forward us the name and possibly the site we could forward this to the administrator.

Hello TheCreeperCow,
I don't quite understand what you mean. The developer's who have made the custom spigot are not allowed to create a fork of spigot? And if so well this has been replicated by many user's due to the fact that I found various version's, while searching for one. Lastly, This spigot is being used by many populated servers and has been sold to many user's
Thanks, PrePay.

**Comment by RedSpeeds** [comment]
He is allowed to create a fork of spigot but he is not allowed to sell it to people for profit.

**Comment by ZeeNatDev** [comment]
> He is allowed to create a fork of spigot but he is not allowed to sell it to people for profit.

Okay well he posted it on a public forums, so if you do a little research using the name of the spigot (In the title). Thanks for the information.

**Comment by ZeeNatDev** [comment]
Also this issue is not resolved but is no longer needed. Thanks for your time.
